### ISSUE TITLE
Expand Browser and Node.js Support in Configuration and Testing

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/hidash#129]
- Expand browser list support (to include more browsers)  
- Include Node.js 18 and above in the browser list  
- Add Node.js versions ~~16~~, 18, 20, and 22 to the test matrix
  - updated https://github.com/NaverPayDev/hidash/issues/129#issuecomment-2497481919

**Comment by yceffort-naver** [comment]
## browserslist

https://browsersl.ist/#q=node+%3E%3D+16%2C+%3E%3D+0.1%25%2C+not+dead%2C+not+op_mini+all&region=KR

![image](https://github.com/user-attachments/assets/cca2a531-9e51-4abc-ba82-a0c68bedbdee)

13%... ?????

**Comment by yujeong-jeon** [comment]
https://browsersl.ist/#q=node+%3E%3D+16%2C+%3E%3D+0.1%25%2C+not+dead%2C+not+op_mini+all%2C+last+3+years&region=KR

혹시 이건..?
![스크린샷 2024-11-22 오후 3 44 51](https://github.com/user-attachments/assets/a2e83397-feda-4384-9776-5fe7ce586821)

**Comment by yceffort-naver** [comment]
https://github.com/NaverPayDev/hidash/issues/129#issuecomment-2492982223
높은 확률로 빌드가 터질것 같은데, (core-js 폴리필 이 필요하다고 해서)

필요한 이유가 정말로 해당 버전에 없는 기능이 아니라면 괜찮을 것 같습니다. 설령 그런 기능이 있다고 하더라도, 우회할 방법이 있다면 우회해서 구현해보겠습니다.

**Comment by yujeong-jeon** [comment]
네엡! 우선 https://github.com/NaverPayDev/hidash/issues/129#issuecomment-2492982223 로 해보겠습니다 🙇‍♀️ 
애매하면 빌드 검사해보고 직접 구현하거나 다른 방법 쓰겠습니다!

**Comment by yceffort-naver** [comment]
100%는 어떻게 해도 못만드나 보군요 그냥 unknown일듯..

![image](https://github.com/user-attachments/assets/f7c04cce-3d18-445f-b9e5-02a2822f20f5)

혹시 제 구현쪽에 터지는거 있으면 말씀해주세요.

**Comment by yujeong-jeon** [comment]
## (24.11.25 Updated) Remove supporting Node.js versions 16

### Why

1. [Node.js 16 is EOL.](https://nodejs.org/en/blog/announcements/nodejs16-eol)

> Following the Node. js 16 end of life on September 11, 2023, we are deprecating Node. js 16 for Builds and Functions on January 31, 2025.

2. pnpm@9.x requires Node.js version at least v18.12
