### ISSUE TITLE
dual package 지원

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/hidash#20]
<img width="663" alt="image" src="https://github.com/user-attachments/assets/1318845f-9065-472c-978c-9bd935b0c0ea">

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/503b5145-890d-419c-8075-914ea026dde4">

nextjs development 모드에서는 HMR 시에 모두 commonjs 로 말아버림... (빌드는 ㄱㅊ)

![image](https://github.com/user-attachments/assets/1080491c-482f-422c-9324-24d0f559e999)

> 아오

cc) @NaverPayDev/frontend

**Comment by 2-one-week** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ

역시 노드 서버 진영은 아직도 cjs가~~

**Comment by yceffort-naver** [comment]
개빡쳐~
