### ISSUE TITLE
map

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/hidash#50]
## map

- **unpkg**: [map](https://unpkg.com/lodash/map.js)
- **lodash**: [Documentation Link](https://lodash.com/docs/4.17.21#map)
- **@types**: [Type Definitions Link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/map.d.ts)

**Comment by yceffort-naver** [comment]
@2-one-week 님 한번해보시곘읍니까..

**Comment by 2-one-week** [comment]
도전~
