### ISSUE TITLE
filter

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/hidash#83]
## filter

- **unpkg**: [filter](https://unpkg.com/lodash/filter.js)
- **lodash**: [Documentation Link](https://lodash.com/docs/4.17.21#filter)
- **@types**: [Type Definitions Link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/filter.d.ts)

**Comment by yujeong-jeon** [comment]
@yceffort-naver 님 오늘 요거까지 나갈 준비하겠습니다
